[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-1430
upload_speed = 460800
lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git
    h2zero/NimBLE-Arduino@^2.3.2
    https://github.com/max22-/ble-keyboard-mouse-client.git
build_flags =
    -D USER_SETUP_LOADED=1
    -include $PROJECT_DIR/include/User_Setup.h
    -include $PROJECT_DIR/include/arduino_compat.h
